//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        public System.Guid Id { get; set; }
        public System.DateTime FechaPrestamo { get; set; }
        public System.DateTime FechaDevolucion { get; set; }
        public System.DateTime FechaEstipuladaDevolucion { get; set; }
        public System.Guid IdLibro { get; set; }
        public System.Guid IdMiembro { get; set; }
    
        public virtual Libro Libro { get; set; }
        public virtual Miembro Miembro { get; set; }
    }
}
