//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        public string Id { get; set; }
        public Nullable<System.DateTime> FechaPrestamo { get; set; }
        public Nullable<System.DateTime> FechaDevolucion { get; set; }
        public Nullable<System.DateTime> FechaEstipuladaDevolucion { get; set; }
        public Nullable<int> IdLibro { get; set; }
        public Nullable<int> IdMiembro { get; set; }
    
        public virtual Libro Libro { get; set; }
        public virtual Miembro Miembro { get; set; }
    }
}
