//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TituloLibro
    {
        public TituloLibro()
        {
            this.Libro = new HashSet<Libro>();
        }
    
        public string ISBN { get; set; }
        public string Titulo { get; set; }
    
        public virtual ICollection<Libro> Libro { get; set; }
    }
}
