//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Miembro
    {
        public Miembro()
        {
            this.Prestamos = new HashSet<Prestamo>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
    
        public virtual Libro Libro { get; set; }
        public virtual ICollection<Prestamo> Prestamos { get; set; }
    }
}
